### ISSUE TITLE
group.groups[0] adds to string variables extra quotes

### ISSUE THREAD

**Issue by aligin** [VeritasSoftware/ts-generic-collections#15]
Hello. I think I've discovered an issue.

When you use string variable for groupBy operator, the value of the "key" of the group is wrapped in quotes after grouping.
I've created an [example app](https://stackblitz.com/edit/angular-playground-xtwmvn?file=app/hello-framework/hello-framework.component.html).

The most valuable code is 
app.ts
```ts
export class HelloFrameworkComponent implements OnInit {
  ...
  public people: any[];

  ngOnInit(): void {
    const data = [
      { name: "Martin", sex: "M", age: 28 },
      { name: "Jane", sex: "F", age: 27 },
      { name: "Thomas", sex: "M", age: 15 },
      { name: "William", sex: "M", age: 78 },
      { name: "Kelly", sex: "F", age: 30 }
    ];

    let list = new List(data);

    this.people = list.groupBy(x => [x.sex]).toArray();
  }
}
```

app.html
```html
<ng-container *ngFor="let group of people">
  <h3>{{ group.groups[0] }}</h3>
  <ul>
    <li *ngFor="let adult of group.list.toArray()">{{ adult.name }}</li>
  </ul>
</ng-container>
```

In the result I receive 
```
"M"
Martin
Thomas
William
"F"
Jane
Kell
```
But it must be
```
M
Martin
Thomas
William
F
Jane
Kell
```

**Comment by VeritasSoftware** [comment]
Hi, good point.

Actually, group by can work with objects.

But, for strings, I have put in a fix.

Please get the latest release 1.0.3 on npm.
