### ISSUE TITLE
Problem with distinct on List

### ISSUE THREAD

**Issue by nunch** [VeritasSoftware/ts-generic-collections#7]
Hello,

I'm using this very usefull package, thank you for it, it's awesome !
There is a small bug in the distinct function, it never executes the equals of the comparer on lists.

I changed it this way, could you please publish a new package with this fix ?

    distinct(comparer: IEqualityComparer<T>) : IEnumerable<T> {
        let uniques = new List<T>();
        this.forEach(x => {
            if(!uniques.any(y => comparer.equals(x, y))){
                uniques.add(x);
            }
        });

        return uniques;
    }

Regards,
Yoann

**Comment by VeritasSoftware** [comment]
Hi Yoann

Great that you like the library. Good to know,

The distinct functionality needs you to implement **IEqualityComparer<T>**
and pass it to the distinct function.

Eg:

```
class EqualityComparer implements IEqualityComparer<number> {
  equals(x: number, y: number) : boolean {
    return x == y;
  }
}
```
You can take a look at the Unit Test on distinct [here](https://github.com/VeritasSoftware/ts-generic-collections/blob/master/projects/ts-generic-collections/src/lib/list.spec.ts).

Regards.

**Comment by nunch** [comment]
Hello,

Your tests fail but you don't see it because you forgot to append .toBeTruthy() after expect functions.
You can debug it and will find that the distinct list is empty because it never goes to equals function.


    distinct(comparer: IEqualityComparer<T>) : IEnumerable<T> {
        let uniques = new List<T>();
        this.forEach(x => {
            // As uniques is empty, it never goes into the forEach and even if it does 
            uniques.forEach(y => {
                // If one is different => unique little bug here :)
                if (!comparer.equals(x, y)) {
                    uniques.add(x);
                }
            });
        });

        return uniques;
    }

Regards,
Yoann

**Comment by VeritasSoftware** [comment]
Lol, forgot toBeTruthy().
Fixed. You can see the check in on github.

Published new package. Version 0.0.3

Let me know if the issue is resolved.
Thanks for helping improve the library.
